title: Greig
author: j_greig
email: james@greig.cc
description: Helping creative people get unstuck.

twitter_username: j_greig
github_username:  j_greig

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings
markdown: kramdown
theme: greig
exclude:
  - Gemfile
  - Gemfile.lock
paginate: 20

# Added by James
gems: ['jekyll-twitter-plugin']
